### ISSUE TITLE
ethereum-cli --getbalance Invalid JSON RPC response from provider

### ISSUE THREAD

**Issue by skazichris** [capitual/eth-cli#7]
ethereum-cli --getbalance

```
/usr/local/lib/node_modules/node-ethereum-wallet/node_modules/ethjs-provider-http/lib/index.js:43
  var responseError = new Error('[ethjs-provider-http] Invalid JSON RPC response from provider\n    host: ' + host + '\n    response: ' + String(request.responseText) + ' ' + JSON.stringify(request.responseText, null, 2) + '\n    responseURL: ' + request.responseURL + '\n    status: ' + request.status + '\n    statusText: ' + request.statusText + '\n  ');
                      ^

Error: [ethjs-provider-http] Invalid JSON RPC response from provider
    host: https://api.myetherapi.com/eth
    response:  ""
    responseURL: undefined
    status: 0
    statusText:

    at invalidResponseError (/usr/local/lib/node_modules/node-ethereum-wallet/node_modules/ethjs-provider-http/lib/index.js:43:23)
    at XMLHttpRequest.request.onreadystatechange (/usr/local/lib/node_modules/node-ethereum-wallet/node_modules/ethjs-provider-http/lib/index.js:88:17)
    at XMLHttpRequestEventTarget.dispatchEvent (/usr/local/lib/node_modules/node-ethereum-wallet/node_modules/xhr2/lib/xhr2.js:64:18)
    at XMLHttpRequest._setReadyState (/usr/local/lib/node_modules/node-ethereum-wallet/node_modules/xhr2/lib/xhr2.js:353:12)
    at XMLHttpRequest._onHttpRequestError (/usr/local/lib/node_modules/node-ethereum-wallet/node_modules/xhr2/lib/xhr2.js:542:12)
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/node-ethereum-wallet/node_modules/xhr2/lib/xhr2.js:413:24)
    at ClientRequest.emit (node:events:390:28)
    at TLSSocket.socketErrorListener (node:_http_client:447:9)
    at TLSSocket.emit (node:events:390:28)
    at emitErrorNT (node:internal/streams/destroy:164:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  value: <ref *1> XMLHttpRequest {
    onloadstart: null,
    onprogress: null,
    onabort: null,
    onerror: null,
    onload: null,
    ontimeout: [Function (anonymous)],
    onloadend: null,
    _listeners: {},
    onreadystatechange: [Function (anonymous)],
    _anonymous: undefined,
    readyState: 4,
    response: null,
    responseText: '',
    responseType: '',
    status: 0,
    statusText: '',
    timeout: 0,
    upload: XMLHttpRequestUpload {
      onloadstart: null,
      onprogress: null,
      onabort: null,
      onerror: null,
      onload: null,
      ontimeout: null,
      onloadend: null,
      _listeners: {},
      _request: [Circular *1],
      _contentType: 'text/plain;charset=UTF-8',
      _body: Buffer(63) [Uint8Array] [
        123,  34, 106, 115, 111, 110, 114, 112,  99,  34,  58,
         34,  50,  46,  48,  34,  44,  34, 105, 100,  34,  58,
         49,  44,  34, 109, 101, 116, 104, 111, 100,  34,  58,
         34, 101, 116, 104,  95,  98, 108, 111,  99, 107,  78,
        117, 109,  98, 101, 114,  34,  44,  34, 112,  97, 114,
         97, 109, 115,  34,  58,  91,  93, 125
      ]
    },
    _method: 'POST',
    _url: Url {
      protocol: 'https:',
      slashes: true,
      auth: null,
      host: 'api.myetherapi.com',
      port: null,
      hostname: 'api.myetherapi.com',
      hash: null,
      search: null,
      query: null,
      pathname: '/eth',
      path: '/eth',
      href: 'https://api.myetherapi.com/eth'
    },
    _sync: false,
    _headers: {
      'Content-Type': 'application/json',
      Connection: 'keep-alive',
      Host: 'api.myetherapi.com',
      'User-Agent': 'Mozilla/5.0 (Darwin x64) node.js/17.0.1 v8/9.5.172.21-node.12',
      'Content-Length': '63'
    },
    _loweredHeaders: { 'content-type': 'Content-Type' },
    _mimeOverride: null,
    _request: null,
    _response: null,
    _responseParts: null,
    _responseHeaders: null,
    _aborting: null,
    _error: null,
    _loadedBytes: 0,
    _totalBytes: 0,
    _lengthComputable: false
  }
}
```

Node.js v17.0.1

**Comment by wrapped-grin** [comment]
Hey there. You might have already figure this out but I am pretty sure that the default provider they have are not working. When I passed in my own provider things worked.
